# Generated by Django 4.2.11 on 2024-05-12 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_moviedetaillink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviedetaillink',
            options={'ordering': ['movie', 'updated_at']},
        ),
        migrations.RemoveField(
            model_name='moviedetaillink',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='moviedetaillink',
            name='movie_name',
        ),
        migrations.AddField(
            model_name='moviedetaillink',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='c_moviedetaillinks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviedetaillink',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='MovieDetailLinks', to='movies.movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviedetaillink',
            name='updated_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='u_moviedetaillinks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
